spring:
  application:
    name: rpa
  datasource:
    url: jdbc:postgresql://localhost:7777/rpa-DB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger/src
  api-docs:
    path: /swagger/docs
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855